name: CI/CD
on:
    push:
        branches: [ci/cd, main]
    pull_request:
        branches: [ci/cd]
jobs:
    code_style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install packages
              run: npm ci

            - name: Eslint and Prettier checks
              run: |
                  npm run lint
                  npm run format
    build-image:
        needs: code_style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Build docker image
              uses: docker/build-push-action@v3
              with:
                  context: ./
                  file: ./Dockerfile
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs_app:latest
                  outputs: type=docker,dest=/tmp/nodejs_app.tar

            - name: Upload docker bin
              uses: actions/upload-artifact@v3
              with:
                  name: nodejs_app
                  path: /tmp/nodejs_app.tar

    push-docker-image:
        needs: build-image
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: nodejs_app
                  path: /tmp

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Load Docker image
              run: |
                  docker load --input /tmp/nodejs_app.tar
            - name: Push Docker image
              run: |
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs_app

    run-docker-image:
        needs: push-docker-image
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Pull
              run: |
                  docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nodejs_app:latest
            - name: Run Docker image
              run: |
                  docker run -p 80:80 -d ${{ secrets.DOCKERHUB_USERNAME }}/nodejs_app
                  docker container ls
            - name: curl
              run: |
                  sleep 5;
                  curl localhost:80
